## Задание 1

In [1]:
import numpy as np

In [2]:
b=np.array([[1,2,3,3,1],[6,8,11,10,7]])

In [3]:
b

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [4]:
b.shape

(2, 5)

In [5]:
a=b.transpose()

In [6]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [7]:
a.shape

(5, 2)

In [8]:
 mean_a=a.mean(axis=0)

In [9]:
mean_a

array([2. , 8.4])

## Задание 2

In [10]:
a_centered=a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Задание 3

In [11]:
a_centered_sp=np.dot(a_centered[0],a_centered[1])
a_centered_sp/(a.shape[0]-1)

0.24000000000000024

## Задание 4

In [12]:
np.cov(a.T)[0,1]

2.0

## Работа с данными в Pandas

## Задание 1

In [13]:
import pandas as pd

In [14]:
authors = pd.DataFrame({'author_id':[1, 2, 3], 'author_name':['Тургенев','Чехов','Островский']}, columns = ['author_id','author_name'])

In [15]:
books=pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],'price':[450, 300, 350, 500, 450, 370, 290]}, columns =['author_id', 'book_title','price'])

In [16]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [17]:
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

## Задание 2

In [18]:
authors_price=pd.merge(authors, books, on ='author_id', how ='inner')

In [19]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [20]:
 top5=authors_price.nlargest(5,'price')

In [21]:
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [64]:
top5.reset_index(inplace=True,drop=True)
top5

author_id author_name         book_title  price
0          2       Чехов   Толстый и тонкий    500
1          1    Тургенев        Отцы и дети    450
2          2       Чехов    Дама с собачкой    450
3          3  Островский              Гроза    370
4          1    Тургенев  Дворянское гнездо    350

## Задание 4

In [60]:
df1=authors_price.groupby('author_name').agg({'price':'min'})
df1

price
author_name       
Островский     290
Тургенев       300
Чехов          450

In [56]:
df2=authors_price.groupby('author_name').agg({'price':'max'})
df2



price
author_name       
Островский     370
Тургенев       450
Чехов          500

In [53]:
df3=authors_price.groupby('author_name').agg({'price':'mean'})
df3

price
author_name            
Островский   330.000000
Тургенев     366.666667
Чехов        475.000000

In [62]:
author_stat=pd.concat([df1,df2,df3], axis=1,ignore_index=True)

In [65]:
author_stat

0    1           2
author_name                      
Островский   290  370  330.000000
Тургенев     300  450  366.666667
Чехов        450  500  475.000000

In [69]:
author_stat=author_stat.rename(columns={0:'min_price',1:'max_price',2:'mean_price'})
author_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

## Задние 5

In [72]:
authors_price['cover']=['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [74]:
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [75]:
?pd.pivot_table 

Signature:
pd.pivot_table(
    data: 'DataFrame',
    values=None,
    index=None,
    columns=None,
    aggfunc: 'AggFuncType' = 'mean',
    fill_value=None,
    margins=False,
    dropna=True,
    margins_name='All',
    observed=False,
    sort=True,
) -> 'DataFrame'
Docstring:
Create a spreadsheet-style pivot table as a DataFrame.

The levels in the pivot table will be stored in MultiIndex objects
(hierarchical indexes) on the index and columns of the result DataFrame.

Parameters
----------
data : DataFrame
values : column to aggregate, optional
index : column, Grouper, array, or list of the previous
    If an array is passed, it must be the same length as the data. The
    list can contain any of the other types (except list).
    Keys to group by on the pivot table index.  If an array is passed,
    it is being used as the same manner as column values.
columns : column, Grouper, array, or list of the previous
    If an array is passed, it must be the same length as the data. The

In [77]:
df=pd.pivot_table(authors_price,index='author_name',columns='cover',values='price',aggfunc=np.sum)
df

cover        мягкая  твердая
author_name                 
Островский    660.0      NaN
Тургенев      650.0    450.0
Чехов           NaN    950.0

In [87]:
df['мягкая'].fillna(0,inplace=True)
df['твердая'].fillna(0,inplace=True)
book_info=df
book_info


cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0

In [88]:
book_info.to_pickle('book_info.pkl')

In [89]:
book_info_2=pd.read_pickle('book_info.pkl')
book_info_2


cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0